# _config.yml

# Optional: Site metadata
title: Jwo Website
description: Jiwon Kim's personal website

# Optional: Set a permalink format
permalink: /:year/:month/:day/:slug/

# Optional: URL for GitHub Pages
url: https://jwo.kim
baseurl: "" # If you're using a project page

# Optional: Other configuration options for plugins, filters, etc.
