# name: Eleventy Build
# on: [push]

# jobs:
#   build_deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#       - name: Build
#         uses: TartanLlama/actions-eleventy@master
#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           publish_dir: _site 
#           publish_branch: gh-pages
#           github_token: ${{ secrets.GITHUB_TOKEN }}

name: Eleventy Build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Site
        run: npx eleventy

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: _site 
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
