name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or master, depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npx @11ty/eleventy  # Adjust based on your build command (11ty might use `npx eleventy`)

      - name: Deploy to GitHub Pages
        run: |
          git remote add origin git@github.com:jwokime/website-2.git
          git checkout -b gh-pages
          cp -R _site/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
